### ISSUE TITLE
Create commands to get, delete and update birthdays

### ISSUE THREAD

**Issue by willy-r** [willy-r/bd-buddy-bot#2]
# About

- Users should be able to execute birthday CRUD to better manage birthday data.

## How to achieve that

Current birthday model

- `id`: auto generate uuid
- `user_id`: discord user id
- `guild_id`: discord server id
- `username`: discord username
- `guild_name`: discord guild display name
- `birthdate`: user birthdate in format ISO YYYY-MM-DD
- `age`: auto generate users age
- `show_age`: should show users age on bot message or get command or not, default to false

### `get` command

User should be able to see his current info from current guild, info that users can get: `user_id`, `username`, `birthdate`, `age`, `show_age`

> Only will show age if `show_age` is **true**

1. Create repository function in file `src/repositores/birthdayRepository.js` called `getBirthdayByUserAndGuild`, that accepts string arguments: `userId (string)`, `guildId (string)`, this functions returns user information based on the rules above.

2. Add command in directory `src/commands/birthday`, this command doesn't have any options since will get current user's interaction, and should verify if user has the birthday role for the guild before getting. After that, should import the `getBirthdayByUserAndGuild` and get user data.
    ![image](https://github.com/willy-r/bd-buddy-bot/assets/47596121/7a4634c1-43b2-4043-aefb-f13ac5288f20)

### `update` command

User should be able to update his birthday info from current guild, info that users can update: `birthdate`, `show_age`

1. Create repository function in file `src/repositores/birthdayRepository.js` called `updateBirthdayByUserAndGuild`, that accepts 3 arguments: `userId (string)`, `guildId (string)` and `birthdayData (object)`, this functions returns updated birthday info.

2. Add command in directory `src/commands/birthday`, this command should accept the exact options like in the **add** command, and should verify if user has the birthday role for the guild before updating. After that, should import the `updateBirthdayByUserAndGuild` and update user data.
    ![image](https://github.com/willy-r/bd-buddy-bot/assets/47596121/7a4634c1-43b2-4043-aefb-f13ac5288f20)
    ![image](https://github.com/willy-r/bd-buddy-bot/assets/47596121/42af9866-43a9-4c18-b6eb-85052f3309cb)

### `delete` command

User should be able to delete his current info from current guild.

1. Create repository function in file `src/repositores/birthdayRepository.js` called `deleteBirthdayByUserAndGuild`, that accepts 2 arguments: `userId (string)`, `guildId (string)`, this functions returns nothing.

2. Add command in directory `src/commands/birthday`, this command doesn't have any options since will get current user's interaction, and should verify if user has the birthday role for the guild before deleting. After that, should import the `deleteBirthdayByUserAndGuild` and delete birthday.
    ![image](https://github.com/willy-r/bd-buddy-bot/assets/47596121/7a4634c1-43b2-4043-aefb-f13ac5288f20)

## Tasks

- [x] Creates `get` command
- [x] Creates `update` command
- [x] Creates `delete` command
